In [1]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Shafique\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.11.0               |   py39haa95532_0        14.4 MB
    ------------------------------------------------------------
                                           Total:        14.4 MB

The following packages will be UPDATED:

  conda                               4.10.3-py39haa95532_0 --> 4.11.0-py39haa95532_0




conda-4.11.0         | 14.4 MB   |            |   0% 
conda-4.11.0         | 14.4 MB   |            |   0% 
conda-4.11.0         | 14.4 MB   | 3          |   3% 
conda-4.11.0         | 14.4 MB   | 6          |   7% 
conda-4.11.0         | 14.4 MB   | #1         |  11% 
conda-4.11.0         | 14.4 MB   | #5         |  15% 
Note: you may need to restart the kernel to use upda

In [2]:
import numpy as np
a = np.array([1, 2, 3])

In [20]:
import numpy as np
a = np.arrange(6)
a2=a[np.newaxis,:]
a2.shape
(1,6)

AttributeError: module 'numpy' has no attribute 'arrange'

In [19]:
import numpy as np
#1D
a = np.array([1, 2, 3])
#2D
a = np.array ([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
import numpy as np
#1D
a = np.array([1, 2, 3,4,5])
a

array([1, 2, 3, 4, 5])

In [16]:
b= np.zeros(2)
b

array([0., 0.])

In [23]:
c= np.ones(3)
c

array([1., 1., 1.])

In [24]:
#Create an empty array with 2 elements 
d=np.empty(3)
d

array([1., 1., 1.])

In [26]:
#with range of elments 
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [27]:
#with specific range of elments 
f=np.arange(2,20)

f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [28]:
#continue
g=np.arange(2,20,2)

g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
#linerly spaces arras
h=np.linspace(0,50, num=5) #gives use nums
h

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [36]:
#Specific data types in array linerly spaces arras

i=np.ones(5, dtype=np.int8) 
i

array([1, 1, 1, 1, 1], dtype=int8)

In [37]:
#linerly spaces arras
j=np.ones(3, dtype=np.float64) 
j

array([1., 1., 1.])

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [41]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
#3D array

#making and rechaing a 3D araay 
c=np.arange(24).reshape(2,3,4)
c


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
#3D array

#making and rechaing a 3D araay 
n=np.arange(30).reshape(2,3,5)
n


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])