In [ ]:
# numpy practice session


In [1]:
#import this library in j.nootbook 
import numpy as np



#Creating an array using numpy



In [5]:
#1-D array 

food=np.array(["Pakorea","Samosa","Raita"])
food

array(['Pakorea', 'Samosa', 'Raita'], dtype='<U7')

In [6]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [7]:
type(price)

numpy.ndarray

In [8]:
type(food)

numpy.ndarray

In [9]:
len(price)

3

In [10]:
len(food)

3

In [12]:
price[0:]

array([5, 5, 5])

In [14]:
food[1]

'Samosa'

In [16]:
price.mean()

5.0

In [19]:
#zeros 
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
#ones 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [23]:
#range 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#specify

np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
#specific interval 
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
#table of 5
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [34]:
#line space
np.linspace (0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
#specify your data type
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [37]:
#for float
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#array Funtions

In [42]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [43]:
#To sort arrany 
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [44]:
b=np.array([10.2,3.4,53.6,45.5])
b

array([10.2,  3.4, 53.6, 45.5])

In [46]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  45.5])

In [50]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6, 100. , 320. ])

#2-D arranys 
    

In [56]:
a=np.array([[1,2,], [5,4]])
a

array([[1, 2],
       [5, 4]])

In [57]:
b=np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [58]:
#Dimension should be same, we can also add different dimmention but there isnew code we need to search
c=np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [59]:
c=np.concatenate((a,b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [70]:
# 2D array with diffeetn funtion 
a=np.array([[[0,1,2,3],
                        [4,5,6,7]],
            
                      [[0,1,2,3],
                       [4,5,6,7]],
            
                    [[0,1,2,3],
                    [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [71]:
#To find the number of dimensions 
a.ndim

3

In [75]:
type(a)

numpy.ndarray

In [73]:
b=np.array([[5,6,7],
           [8,9,10], 
           [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [74]:
b.ndim

2

In [76]:
#Size (number of elements)

a.size

24

In [78]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [77]:
#Shape
a.shape

(3, 2, 4)

In [83]:
a=np.arange(9)  #3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
#Reshape

b=a.reshape (3,3)  #3*3=9
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
#Reshape

np.reshape (a,newshape=(1,9), order="C") 


array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [87]:
#Covert 1D into 2D

a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a.shape

(9,)

In [90]:
#Row wise 2D coversion 

b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [91]:
b.shape


(1, 9)

In [92]:
#column wise 2D coversion 
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [93]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a

In [98]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [99]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [100]:
a.sum()

45

In [103]:
a.mean()

5.0